version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - DATABASE_ADDRESS=${DATABASE_ADDRESS}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env

    restart: always

